### ISSUE TITLE
Use of deprecated Deno API's

### ISSUE THREAD

**Issue by jtoppine** [dyedgreen/deno-sqlite#255]
Starting with Deno 1.40, deno prints out a lot of warnings about the use of deprecated APIs in sqlite module. 

Below is a sample of the warnings (I removed some probably unnecessary wasm stack traces in order to condense the output a bit). 

```
warning: Use of deprecated "Deno.seekSync()" API. This API will be removed in Deno 2.
Stack trace:
  at js_write (https://deno.land/x/sqlite@v3.8/build/vfs.js:58:12)
  at <anonymous> (wasm://wasm/0028679a:1:5980)
hint: Use `file.seekSync()` instead.
hint: It appears this API is used by a remote dependency. Try upgrading to the latest version of that dependency.
warning: Use of deprecated "Deno.writeSync()" API. This API will be removed in Deno 2.
Stack trace:
  at js_write (https://deno.land/x/sqlite@v3.8/build/vfs.js:59:19)
  at <anonymous> (wasm://wasm/0028679a:1:5980)
hint: Use `writer.writeSync()` instead.
hint: It appears this API is used by a remote dependency. Try upgrading to the latest version of that dependency.
warning: Use of deprecated "Deno.seekSync()" API. This API will be removed in Deno 2.
Stack trace:
  at js_write (https://deno.land/x/sqlite@v3.8/build/vfs.js:58:12)
  at <anonymous> (wasm://wasm/0028679a:1:5980)
hint: Use `file.seekSync()` instead.
hint: It appears this API is used by a remote dependency. Try upgrading to the latest version of that dependency.
warning: Use of deprecated "Deno.writeSync()" API. This API will be removed in Deno 2.
Stack trace:
  at js_write (https://deno.land/x/sqlite@v3.8/build/vfs.js:59:19)
  at <anonymous> (wasm://wasm/0028679a:1:5980)
hint: Use `writer.writeSync()` instead.
```

**Comment by dyedgreen** [comment]
Yeah, this looks like we should just swap out the deprecated functions.
